# see: https://squidfunk.github.io/mkdocs-material
site_name: PAGOS
site_description: PAGOS Documentation
site_url: https://teampagos.github.io/pagos
repo_name: PAGOS
repo_url: https://github.com/TeamPAGOS/PAGOS

theme:
  name: material
  logo: img/PAGOS_Logo_O_Bright-cropped.svg
  favicon: img/PAGOS_logo_O_Bright2-cropped.svg
  icon:
    annotation: material/information

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.share
  
plugins:
  - search

markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.highlight:
        line_spans: __span
        use_pygments: true
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.snippets:
        base_path: docs/snippets
        check_paths: true
    - pymdownx.arithmatex:
        generic: true

extra:
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js